version: '3.8'

services:
  cannoli-reviews:
    build: .
    ports:
      - "8001:8001"
    environment:
      - DATABASE_URL=sqlite:///cannolireviews.db
    volumes:
      - ./data:/app/data
      - ./static:/app/static
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8001/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s 
