name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.0
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}

      - name: Set execute permission for deploy.sh
        run: chmod +x deploy.sh

      - name: Deploy to EC2
        run: |
          ssh ec2-user@ec2-3-91-16-48.compute-1.amazonaws.com 'bash -s' < _infra/deploy.sh
