name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to EC2
        env:
          EC2_USER: ${{ secrets.EC2_USER }}
          EC2_HOST: ${{ secrets.EC2_HOST }}
          EC2_SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
        run: |
          echo "$EC2_SSH_PRIVATE_KEY" > .ssh/private_key.pem && chmod 600 .ssh/private_key.pem
          ssh -o StrictHostKeyChecking=no -i ".ssh/private_key.pem" $EC2_USER@$EC2_HOST 'bash -s' < _infra/deploy.sh
